update loadAudioFiles
cpp-lln-lab/localizer_auditory_motion pull request #22
Opened 2020-08-25 13:42 UTC by marcobarilari

still in WIP, it will break up things since the expDesign is not still ready to accommodate the new design (motionLRL and motion RLR). I will PR to this PR soon

2020-08-25 15:13 UTC, marcobarilari commented
ok, made a bit of confusion... I cannot send a pr to this pr. You see all the commits that make these changes working here

2020-08-25 15:32 UTC, marcobarilari commented
`equateRMSWav` is far away to be at a good refactoring level, it is there so that we can start working with the new sounds

2020-08-26 09:42 UTC, Remi-Gau requested changes
Only added a stub for a help section but that looks good to me.

2020-08-26 09:42 UTC, Remi-Gau commented on initEnv.m
> +    addpath(fullfile(pth, 'input'));
```suggestion
```

2020-08-26 09:42 UTC, Remi-Gau commented on initEnv.m
> +    addpath(fullfile(pth, 'input'));
removing this as it seems to be not needed

2020-08-26 09:42 UTC, Remi-Gau commented on input/equateRmsWav.m
> +
```suggestion
% function equateRmsWav(subjName)
% Not used during the experiment itself but allows to root mean square the sounds of a given subject.
```

2020-08-26 09:42 UTC, Remi-Gau commented on input/equateRmsWav.m
> +function runFunction (referenceWavFn, targetWavFn)
This looks like a good candidate to take out of this and put in CPP_PTB. 

Not urgent can be done later.

2020-08-26 09:47 UTC, Remi-Gau approved these changes

2020-08-26 09:57 UTC, merged